"""Shared helpers for every script in the notes.

Every script does

    import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
    from common import setup, savefig, save_numbers, rng_for, SERIES

so that figures, numbers and random streams are handled the same way everywhere.

* ``savefig(fig, "ch06", "name")``  writes figures/ch06/name.pdf  (vector, for LaTeX)
* ``save_numbers("ch06", "name", {"VarRatio": 1.003})``  writes results/ch06/name.tex
  containing ``\\newcommand{\\VarRatio}{1.003}`` -- the text then quotes the
  number the code actually produced, so notes and code never drift apart.
* ``rng_for("ch06", "name")``  a numpy Generator seeded reproducibly from the
  script name: rerunning a script reproduces every figure bit-for-bit.
"""
from __future__ import annotations

import hashlib
import os
import pathlib

# keep numerical libraries from oversubscribing the machine when several scripts run at once
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_v, "4")

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

NOTES = pathlib.Path(__file__).resolve().parents[1]
FIG = NOTES / "figures"
RES = NOTES / "results"
# Seed test: SEED_SALT=1 (or 2, ...) shifts every seed and sends figures and numbers to
# build/seedtest_<salt>/ so the book's own results are untouched. Unset: the book's seeds.
SEED_SALT = os.environ.get("SEED_SALT", "")
if SEED_SALT:
    FIG = NOTES / "build" / f"seedtest_{SEED_SALT}" / "figures"
    RES = NOTES / "build" / f"seedtest_{SEED_SALT}" / "results"
DATA = NOTES / "data"          # cached expensive products (CAMB spectra, simulated maps, chains)

# Categorical order is fixed: slot 1 is always the first series, never cycled.
SERIES = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
INK = "#0b0b0b"          # primary text
INK2 = "#52514e"         # secondary text, axes
GRID = "#e4e3df"         # recessive grid
THEORY = "#0b0b0b"       # analytic / theoretical curve: black, dashed
SEQ = "Blues"            # sequential colormap (magnitude)
DIV = "RdBu_r"           # diverging colormap (correlations, residuals), centred on zero


def setup(width: float = 6.0, height: float = 3.8):
    """Apply the house matplotlib style; returns the default figsize."""
    plt.rcParams.update({
        "figure.figsize": (width, height),
        "figure.dpi": 150,
        "savefig.bbox": "tight",
        "font.family": "serif",
        "font.size": 10,
        "mathtext.fontset": "cm",
        "axes.prop_cycle": matplotlib.cycler(color=SERIES),
        "axes.edgecolor": INK2,
        "axes.labelcolor": INK,
        "axes.titlesize": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.color": GRID,
        "grid.linewidth": 0.6,
        "xtick.color": INK2,
        "ytick.color": INK2,
        "lines.linewidth": 1.6,
        "lines.markersize": 4,
        "legend.frameon": False,
        "legend.fontsize": 9,
        "image.cmap": SEQ,
    })
    return (width, height)


def savefig(fig, chapter: str, name: str):
    out = FIG / chapter
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{name}.pdf"
    fig.savefig(path)
    plt.close(fig)
    print(f"[figure] {path.relative_to(NOTES)}")
    return path


def _fmt(v):
    if isinstance(v, str):
        return v
    if isinstance(v, (int, np.integer)):
        return f"{int(v)}"
    v = float(v)
    if v != 0 and (abs(v) < 1e-3 or abs(v) >= 1e5):
        m, e = f"{v:.3e}".split("e")
        return rf"{m}\times10^{{{int(e)}}}"
    return f"{v:.4g}"


def save_numbers(chapter: str, name: str, values: dict):
    """Write LaTeX macros. Macro names must be letters only (LaTeX rule), e.g. 'VarRatioL'.

    Values are typeset in math mode by the chapter:  $\\VarRatioL$.
    """
    out = RES / chapter
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{name}.tex"
    lines = [f"% generated by code/{chapter}/{name}.py -- do not edit"]
    for k, v in values.items():
        assert k.isalpha(), f"LaTeX macro names must be letters only: {k!r}"
        lines.append(f"\\providecommand{{\\{k}}}{{}}\\renewcommand{{\\{k}}}{{{_fmt(v)}}}")
    path.write_text("\n".join(lines) + "\n")
    print(f"[numbers] {path.relative_to(NOTES)}")
    return path


def rng_for(chapter: str, name: str, stream: int = 0) -> np.random.Generator:
    """Reproducible PCG64 generator seeded from the script identity (+ optional stream index)."""
    key = f"{chapter}/{name}" + (f"/salt{SEED_SALT}" if SEED_SALT else "")
    seed = int.from_bytes(hashlib.sha256(key.encode()).digest()[:8], "little")
    return np.random.Generator(np.random.PCG64(np.random.SeedSequence([seed, stream])))


def theory_line(ax, x, y, label="theory", **kw):
    """Analytic curves are always black dashed, drawn on top of simulations."""
    return ax.plot(x, y, color=THEORY, ls="--", lw=1.4, label=label, zorder=5, **kw)
